version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - common_network

networks:
  common_network:
    external: true
